# Generated by Django 3.2.12 on 2022-07-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0002_auto_20220715_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('job_role', models.CharField(blank=True, max_length=255, verbose_name='Job Role')),
                ('job_description', models.TextField(blank=True, verbose_name='Job Description')),
                ('monthly_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Monthly Pay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Current Residential Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.CharField(blank=True, max_length=255, verbose_name='BVN'),
        ),
        migrations.AddField(
            model_name='user',
            name='certified',
            field=models.BooleanField(default=False, verbose_name='Certified'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='employed',
            field=models.DateField(blank=True, null=True, verbose_name='Employed Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='executive',
            field=models.BooleanField(default=False, verbose_name='Executive'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('EMPLOYED', 'EMPLOYED'), ('PROBATION', 'PROBATION'), ('SACKED', 'SACKED'), ('UNEMPLOYED', 'UNEMPLOYED'), ('RETIRED', 'RETIRED'), ('APPLICANT', 'APPLICANT')], default='UNEMPLOYED', max_length=255, verbose_name='Employment Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='unemployed',
            field=models.DateField(blank=True, null=True, verbose_name='Unemployed Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='eg: 018276475673', max_length=17, unique=True),
        ),
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(choices=[('MR', 'MR'), ('MISS', 'MISS'), ('MRS', 'MRS'), ('Ms', 'Ms')], max_length=255, verbose_name='Mr/Mrs/Ms/Miss')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Kin')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Kin Address')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Kin Email')),
                ('kin_type', models.CharField(choices=[('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('SPOUSE', 'SPOUSE'), ('CHILD', 'CHILD'), ('FRIEND', 'FRIEND')], default='SPOUSE', max_length=255, verbose_name='Kin Type')),
                ('phone', models.CharField(blank=True, help_text='eg: 018276475673', max_length=17, unique=True)),
                ('dp', stdimage.models.StdImageField(blank=True, upload_to='user/kin/dp')),
                ('country', models.ForeignKey(blank=True, default='NG', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries_plus.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('job_requirement', models.CharField(blank=True, max_length=255, verbose_name='Job Requirement')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='users.jobrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.jobrole'),
        ),
    ]
