# Generated by Django 3.2.12 on 2022-08-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220728_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'EMPLOYED'), ('PROBATION', 'PROBATION'), ('SACKED', 'SACKED'), ('UNEMPLOYED', 'UNEMPLOYED'), ('RETIRED', 'RETIRED'), ('APPLICANT', 'APPLICANT')], default='UNEMPLOYED', max_length=255, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('STAFF', 'Staff'), ('CONTRATOR', 'Contractor'), ('CLIENT', 'Client'), ('INTERN', 'Intern'), ('ADMINISTRATION', 'Administration'), ('NOTYPE', 'No Type')], default='CLIENT', max_length=255, verbose_name='Permission Type'),
        ),
    ]
