# Generated by Django 3.2.12 on 2022-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220803_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='eg: 018276475673', max_length=17),
        ),
    ]
