# Generated by Django 3.2.12 on 2022-07-23 08:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('company', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('subscribed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
