# Generated by Django 3.2.12 on 2022-07-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_category_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='can_comment',
        ),
    ]
