# Generated by Django 3.2.12 on 2022-07-29 20:15

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20220729_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('pdf', models.FileField(upload_to='bulletin/')),
                ('draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletin',
                'ordering': ['-published'],
                'managed': True,
            },
        ),
    ]
