# Generated by Django 3.2.12 on 2022-07-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_bulletin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
