# Generated by Django 3.2.12 on 2022-07-23 08:05

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20220722_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Consent',
                'verbose_name_plural': 'Consents',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('details', models.TextField()),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Noticeboard',
                'verbose_name_plural': 'Noticeboard',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
