# Generated by Django 3.2.12 on 2022-07-23 08:35

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_auto_20220723_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='services/image/'),
        ),
    ]
