# Generated by Django 3.2.12 on 2022-07-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_noticeboard_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='ip',
        ),
    ]
