# Generated by Django 3.2.12 on 2022-07-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0006_remove_noticeboard_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='slug',
        ),
    ]
