# Generated by Django 3.2.12 on 2022-07-24 02:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_remove_noticeboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='caption1',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='caption2',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='caption3',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
