# Generated by Django 3.2.12 on 2022-07-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0009_auto_20220728_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='caption1',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='title1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='caption2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='caption3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title3',
        ),
    ]
