# Generated by Django 3.2.12 on 2022-07-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0011_auto_20220730_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certifications',
            old_name='logo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='logo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='certifications',
            name='claims',
            field=models.URLField(blank=True, help_text='Link to verify the certification'),
        ),
    ]
