# Generated by Django 3.2.12 on 2022-07-30 04:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0012_auto_20220730_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('logo', stdimage.models.StdImageField(upload_to='membership/image/')),
                ('website', models.URLField(blank=True, help_text='Link to partners official website')),
            ],
            options={
                'verbose_name': 'Partnership',
                'verbose_name_plural': 'Partnerships',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
