# Generated by Django 3.2.12 on 2022-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0013_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='staticpages',
            name='title',
            field=models.CharField(blank=True, help_text='eg. Privacy Policy, Terms of Business, Cookies Policy, Vendor Code of Conduct, Code of Conduct', max_length=250),
        ),
    ]
